# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               CDBradley
tagline:             'A personal blog'
description:         'A place where you can follow my learning new skills and find resources to learn them yourself.'
url:                 http://lanyon.getpoole.com
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Colt Bradley
  url:               
  email:             coltbradley@gmail.com

# Custom vars
version:             1.0.0
