# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               CDBradley
tagline:             'A personal blog'
description:         'A place for my thoughts, musings, and what I`m working on.'
url:                 http://www.cdbradley.com
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Colt Bradley
  url:               http://www.cdbradley.com
  email:             coltbradley@gmail.com

# Custom vars
version:             1.0.0
